"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const drawAddress = (doc, x, y, data) => {
    let posX = x;
    let posY = y;
    doc.setFontSize(12);
    doc.setFont("KanitMedium", "normal");
    const lineHeight = doc.getTextDimensions("Some").h + 1;
    posY += lineHeight;
    doc.text(data.name, posX, posY);
    doc.setFont("KanitLight", "normal");
    posY += lineHeight;
    doc.text(data.address.line1, posX, posY);
    posY += lineHeight;
    doc.text(data.address.line2, posX, posY);
    posY += lineHeight;
    doc.text(data.address.postcode, posX, posY);
    posY += lineHeight;
    doc.text(data.address.country, posX, posY);
    return posY + lineHeight;
};
exports.default = drawAddress;
