"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const colors_1 = require("../resources/colors/colors");
const drawOwnAddress = (doc, x, y, data) => {
    let posX = x;
    let posY = y;
    doc.setFontSize(10);
    doc.setTextColor(colors_1.colors.blue);
    doc.setFont("KanitMedium", "normal");
    doc.text(data.name + " | ", posX, posY);
    posX += doc.getTextDimensions(data.name + " | ").w;
    doc.text(data.address.line1 + " | ", posX, posY);
    posX += doc.getTextDimensions(data.address.line1 + " | ").w;
    doc.text(data.address.postcode + ", ", posX, posY);
    posX += doc.getTextDimensions(data.address.postcode + ", ").w;
    doc.text(data.address.line2, posX, posY);
    posX += doc.getTextDimensions(data.address.line2).w;
    doc.setFontSize(12);
    doc.setTextColor(colors_1.colors.dark);
};
exports.default = drawOwnAddress;
